stages:
  - dev
  - test
  - deploy

cache:
  paths:
    - node_modules/* # 緩存不經常更改的內容

#dev:
#  stage: test
#  tags:
#    - fe-cookbook
#
#test:
#  stage: test
#  tags:
#    - fe-cookbook

deploy:
  stage: deploy
  tags:
    - fe-cookbook
  only:
    - master
  script:
    - echo 安装依赖...
    - gitbook install
    - echo 初始化文件...
    - gitbook init
    - echo 正在生成静态文件...
    - gitbook build
    - echo 完成构建，正在部署...
#    配置 ssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_dxhyfe
    - chmod 600 ~/.ssh/id_rsa_dxhyfe
    - echo -e "Host $SERVER_USER_HOST\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa_dxhyfe\n\n" > ~/.ssh/config
#    拷贝文件【scp是secure copy的缩写, scp是linux系统下基于ssh登陆进行安全的远程文件拷贝命令。】
    - scp -o stricthostkeychecking=no -r _book/* root@${SERVER_USER_HOST}:${SERVER_MASTER_PATH}
